# Generated by Django 4.1 on 2022-08-17 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioSeguido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguindo', to='core.usuario')),
                ('usuarioSeguidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seguidores', to='core.usuario')),
            ],
        ),
    ]
