# Generated by Django 4.1 on 2022-09-14 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='noticia_idnoticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='core.noticia'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='user_iduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='curtida',
            name='idnoticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curtidas', to='core.noticia'),
        ),
        migrations.AlterField(
            model_name='curtida',
            name='iduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curtidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='topico_idtopico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noticias', to='core.topico'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='user_iduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noticias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Midia_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midiabannerpath', models.CharField(max_length=5000)),
                ('midiaprofilepath', models.CharField(max_length=5000)),
                ('user_iduser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='midia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
