# Generated by Django 4.1.1 on 2022-09-06 17:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seguir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nometopico', models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterModelOptions(
            name='seguir',
            options={'verbose_name_plural': 'Seguir'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='img',
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticiatitulo', models.CharField(max_length=180)),
                ('texto', models.CharField(max_length=7000)),
                ('noticiadatacadastro', models.DateField(default=datetime.datetime.now)),
                ('topico_idtopico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.topico')),
                ('user_iduser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.usuario')),
            ],
        ),
    ]
