# Generated by Django 4.1 on 2022-09-14 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_comentario_noticia_idnoticia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midiapath', models.CharField(max_length=5000)),
                ('noticia_idnoticia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='midia', to='core.noticia')),
            ],
        ),
    ]
