# Generated by Django 4.1.1 on 2022-10-10 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_midia_user_user_iduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='datacomentario',
            field=models.DateField(default='2022-10-10'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='noticia_idnoticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midia', to='core.noticia'),
        ),
    ]
